sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1410
    #阿里云参数
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAy5ThL8KRPuAPi54m6
    access-key-secret: V5U5EjZJL05q5oCOl7vO6PaFJtascS
    bucket-name: web-tlias1410